### ISSUE TITLE
[FEATURE]: Add support for RAID0 (striping)

### ISSUE THREAD

**Issue by s3rj1k** [minio/radio#2]
Please consider adding support for bucket based striping using configurable stripping map.

**Comment by harshavardhana** [comment]
Radio's intention is to provide redundancy, striping is not the goal.

**Comment by s3rj1k** [comment]
@harshavardhana Are there any plans to write product for stripping?
Or maybe there are readily available solutions that can provide such a feature?

**Comment by harshavardhana** [comment]
> @harshavardhana Are there any plans to write product for stripping?
> Or maybe there are readily available solutions that can provide such a feature?

@s3rj1k there are none - it's not something we are interested in doing.
